# Copyright (c) 2022 Institute of Software, Chinese Academy of Sciences (ISCAS)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM debian

ARG CI_COMMIT_SHA
ARG CI_PIPELINE_ID
ENV CI_COMMIT_SHA=${CI_COMMIT_SHA}
ENV CI_PIPELINE_ID=${CI_PIPELINE_ID}
ENV TZ=Asia/Shanghai

RUN apt update && DEBIAN_FRONTEND=noninteractive TZ=Asia/Shanghai apt-get -y install tzdata ca-certificates && rm -rf /var/lib/apt/lists/*

COPY release/*-client /
RUN cp /linux-`arch`-client /usr/bin/client && rm -rf /*-client
COPY entrypoint-client.sh /opt/entrypoint.sh
RUN chmod +x /opt/entrypoint.sh

ENTRYPOINT ["/opt/entrypoint.sh"]
